import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';

import '@/app/_styles/globals.css';
import Footer from '@/app/_components/layout/Footer';
import Header from '@/app/_components/layout/Header';

const textNoto = Noto_Sans_KR({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Our Trip',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  // review,
}: Readonly<{
  children: React.ReactNode;
  // review: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        // className={`${textNoto.className} grid min-h-screen w-full grid-rows-[10rem_15rem_1fr_30rem] antialiased`}
        // className={`${textNoto.className} grid min-h-screen w-full grid-rows-[10rem_1fr_30rem] antialiased`}
        className={`${textNoto.className} flex min-h-screen w-full flex-col antialiased`}
      >
        <Header />

        {/* <MainNav /> */}
        <div className="h-full w-full">{children}</div>
        {/* <div>{review}</div> */}
        <Footer />
      </body>
    </html>
  );
}
