import type { Metadata } from 'next';
import { Sunflower, Noto_Sans_KR } from 'next/font/google';

import '@/app/_styles/globals.css';
import Header from '@/app/_components/layout/Header';
import Nav from '@/app/_components/layout/MainNav';
import MainNav from '@/app/_components/layout/MainNav';
import Footer from './_components/layout/Footer';

const textNoto = Noto_Sans_KR({
  subsets: ['latin'],
  display: 'swap',
  weight: '300',
});

export const metadata: Metadata = {
  title: 'Our Trip',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${textNoto.className} grid h-dvh min-h-screen w-screen grid-rows-[10rem_15rem_1fr_30rem] antialiased`}
      >
        <Header />
        <MainNav />
        <main className="h-full w-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
